name: DevSecOps

on:
  workflow_dispatch:
    inputs:
      testing:
        type: choice
        options:
          - DevOps
          - SAST/SCA
          - DAST/IAST
        required: true  

jobs:

  secret-leaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: trufflehog
      run: docker run --rm -t -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  filesystem /pwd/lib/ | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' >> $GITHUB_STEP_SUMMARY

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: semgrep
        run: docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep scan --config="r/javascript.sequelize.security.audit.sequelize-injection-express.express-sequelize-injection" --emacs *    >>    $GITHUB_STEP_SUMMARY            

  terrascan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: terrascan
        run: docker run --rm -t -v  "${PWD}:/pwd" tenable/terrascan scan -i cft -d /pwd/aws | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' >> $GITHUB_STEP_SUMMARY || exit 0

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "npm build"
        run: echo "Build complete"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Execute unit tests and smoke tests"
        run: echo "Test complete"

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare Docker image"
        run: echo "Image pushed"

  akto-api:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: akto-api-dashboard
        env:
          AKTO_API_KEY: ${{ secrets.AKTO_API_KEY }}
        run: | 
          curl "https://app.akto.io/api/startTest" -H 'X-API-KEY: wOFLu4YPbhySI44u3BJTIMtvNnHWwxiHzTBcR3TA' -H 'content-type: application/json' -d '{"testingRunHexId": "6538807eb0c62f3ac225ab62", "startTimestamp" : 0,"metadata": {"platform": "Github Actions"}}'  --compressed


  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: "Trigger deployment"
        run: echo "Deployed successfully"
