name: DevSecOps

on:
  workflow_dispatch:
    inputs:
      testing:
        type: choice
        options:
          - SAST/SCA
          - DAST/IAST
        required: true  

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - name: "Execute smoke test on Docker"
        run: docker-compose -f docker-compose.test.yml up --exit-code-from sut


