name: DevSecOps

on:
  workflow_dispatch:
    inputs:
      testing:
        type: choice
        options:
          - SAST/SCA
          - DAST/IAST
        required: true  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "npm build"
        run: echo "Build complete"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Execute unit tests and smoke tests"
        run: echo "Test complete"

  package:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare Docker image"
        run: echo "Image pushed"


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger deployment"
        run: echo "Deployed successfully"


